### ISSUE TITLE
[동혁] FloatingButton 컴포넌트 구현

### ISSUE THREAD

**Issue by h2s0** [potenday-project/promise-me-frontend#42]
# 플로팅버튼 컴포넌트

## 디자인 시안
![image](https://github.com/potenday-project/promise-me-frontend/assets/74224516/ad3b3f35-8f1d-49bb-9f88-5e824813dc46)
![image](https://github.com/potenday-project/promise-me-frontend/assets/74224516/86188615-1862-47dd-882b-0274fc39bc77)

1- 준비 상태.
2- 1.회의 녹음하기
2- 2.회의록 직접 쓰기

**Comment by dongapple** [comment]
## 제작 컴포넌트 
![image](https://github.com/potenday-project/promise-me-frontend/assets/74224516/d7763220-ec03-4660-9cab-68acb3d4ff65)

1- 준비상태.

![image](https://github.com/potenday-project/promise-me-frontend/assets/74224516/ab5da8cc-8f29-4a92-8a8a-7f7284251637)

2- 이동상태. 


## 사용 방법
![image](https://github.com/potenday-project/promise-me-frontend/assets/74224516/61616a6c-d130-4476-a863-f703c75b4d9d)
컴포넌트 입력 끝...
