### ISSUE TITLE
[동혁] ProgressIndicator 컴포넌트 구현

### ISSUE THREAD

**Issue by h2s0** [potenday-project/promise-me-frontend#48]
시안

![image](https://github.com/potenday-project/promise-me-frontend/assets/134567479/03941d53-36c8-4065-8064-5a11d4e34bbe)

**Comment by dongapple** [comment]
## 구현된 디자인

![image](https://github.com/potenday-project/promise-me-frontend/assets/74224516/42439232-7de2-49a9-ba78-2cac1d0f1ff1)

## 사용법
![image](https://github.com/potenday-project/promise-me-frontend/assets/74224516/bf025f78-d3d9-4403-b5b9-3940907db58e)

퍼센트 입력 끝...
이미지 없어서 추후 수정 필요
